# Generated by Django 5.1.5 on 2025-02-17 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('completed', models.IntegerField(default=0)),
                ('output_file_name', models.CharField(max_length=500)),
                ('initial_count', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('spam_block_retries', models.IntegerField(blank=True, null=True)),
                ('valid_email_retries', models.IntegerField(blank=True, null=True)),
                ('part1', models.TextField(blank=True, null=True)),
                ('part2', models.TextField(blank=True, null=True)),
                ('part3', models.TextField(blank=True, null=True)),
                ('part4', models.TextField(blank=True, null=True)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('wpuser_id', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('results', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CatchAllDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=50, unique=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoMXDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=50, unique=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpuser_id', models.IntegerField(unique=True)),
                ('api_key', models.CharField(blank=True, max_length=16, null=True, unique=True)),
            ],
        ),
    ]
