# Generated by Django 5.1.5 on 2025-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtask',
            name='output_file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
